In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
true_data = pd.read_csv("real.csv")

In [4]:
fake_data = pd.read_csv("fake.csv")

C:\Users\Dilson\AppData\Local\Temp\ipykernel_5940\715263091.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  fake_data = pd.read_csv("fake.csv")

In [5]:
true_data

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [6]:
fake_data

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Yearâ...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obamaâ€™s Na...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23497,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23498,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23499,Sunnistan: US and Allied â€˜Safe Zoneâ€™ Plan ...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23500,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23501,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
true_data["label"] = 0
fake_data["label"] = 1

In [8]:
true_data

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [9]:
fake_data

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,label
0,Donald Trump Sends Out Embarrassing New Yearâ...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,Trump Is So Obsessed He Even Has Obamaâ€™s Na...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23497,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23498,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23499,Sunnistan: US and Allied â€˜Safe Zoneâ€™ Plan ...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23500,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23501,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [10]:
dataset1 =  fake_data[['text','label']]

In [11]:
dataset2 = true_data[['text','label']]

In [12]:
dataset1

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      1
1      House Intelligence Committee Chairman Devin Nu...      1
2      On Friday, it was revealed that former Milwauk...      1
3      On Christmas day, Donald Trump announced that ...      1
4      Pope Francis used his annual Christmas Day mes...      1
...                                                  ...    ...
23497  21st Century Wire says As 21WIRE reported earl...      1
23498  21st Century Wire says It s a familiar theme. ...      1
23499  Patrick Henningsen  21st Century WireRemember ...      1
23500  21st Century Wire says Al Jazeera America will...      1
23501  21st Century Wire says As 21WIRE predicted in ...      1

[23502 rows x 2 columns]

In [13]:
dataset2

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      0
21413  LONDON (Reuters) - LexisNexis, a provider of l...      0
21414  MINSK (Reuters) - In the shadow of disused Sov...      0
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      0
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      0

[21417 rows x 2 columns]

In [14]:
dataset = pd.concat([dataset1,dataset2])

In [15]:
dataset

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      1
1      House Intelligence Committee Chairman Devin Nu...      1
2      On Friday, it was revealed that former Milwauk...      1
3      On Christmas day, Donald Trump announced that ...      1
4      Pope Francis used his annual Christmas Day mes...      1
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      0
21413  LONDON (Reuters) - LexisNexis, a provider of l...      0
21414  MINSK (Reuters) - In the shadow of disused Sov...      0
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      0
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      0

[44919 rows x 2 columns]

In [16]:
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [17]:
dataset.value_counts("label")

label
1    23502
0    21417
Name: count, dtype: int64

In [18]:
dataset = dataset.sample(frac = 1)

In [19]:
dataset

                                                    text  label
20844  Wait for the Left to blame micro-aggressions b...      1
20486  WASHINGTON (Reuters) - A powerful sea surge wi...      0
13318  POTSDAM, Germany (Reuters) - German police on ...      0
18399  STRASBOURG (Reuters) - The European Parliament...      0
3759   MEXICO CITY (Reuters) - Mexican Economy Minist...      0
...                                                  ...    ...
4900   CHICAGO (Reuters) - Agriculture leaders includ...      0
12074  Two days before the Berlin killings resurrecte...      1
6363   It s always been obvious to people with half a...      1
13138  MANILA (Reuters) - Philippine President Rodrig...      0
14435  Stuart Varney hammers a cuckoo super delegate ...      1

[44919 rows x 2 columns]

In [20]:
import nltk
import re

In [21]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [22]:
ps = WordNetLemmatizer()

In [23]:
stopwords = stopwords.words("english")

In [24]:
def clean_row(row):
    row = row.lower()
    row = re.sub('[^a-zA-Z]', ' ',row)
    token = row.split()
    news = [ps.lemmatize(word) for word in token if not word in stopwords]
    cleaned_news = ' '.join(news)
    return cleaned_news

In [25]:
dataset['text'] = dataset['text'].apply(lambda x: clean_row(x))

In [26]:
dataset['text']

20844    wait left blame micro aggression insensitive n...
20486    washington reuters powerful sea surge accompan...
13318    potsdam germany reuters german police friday s...
18399    strasbourg reuters european parliament savaged...
3759     mexico city reuters mexican economy minister i...
                               ...
4900     chicago reuters agriculture leader including l...
12074    two day berlin killing resurrected darkest per...
6363     always obvious people half clue better hatred ...
13138    manila reuters philippine president rodrigo du...
14435    stuart varney hammer cuckoo super delegate ber...
Name: text, Length: 44919, dtype: object

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
vectorizer = TfidfVectorizer(max_features = 50000, lowercase = False, ngram_range = (1,2))

In [29]:
x =  dataset.iloc[:35000,0]

In [30]:
y = dataset.iloc[:35000,1]

In [31]:
x

20844    wait left blame micro aggression insensitive n...
20486    washington reuters powerful sea surge accompan...
13318    potsdam germany reuters german police friday s...
18399    strasbourg reuters european parliament savaged...
3759     mexico city reuters mexican economy minister i...
                               ...
19098    president donald trump returned cpac friday re...
4036     newt gingrich got owned lady view tuesday nigh...
18493    mark steyn fire last night lucky enough hear b...
20160    blame losing cool crooked lying hillary share ...
13638    woman want president stooping low demanding fr...
Name: text, Length: 35000, dtype: object

In [32]:
y

20844    1
20486    0
13318    0
18399    0
3759     0
        ..
19098    1
4036     1
18493    1
20160    1
13638    1
Name: label, Length: 35000, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
train_data, test_data, train_label, test_label = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [35]:
train_data

17960    guiglo ivory coast reuters ethnic fueled land ...
2718     canadian prime minister justin trudeau diploma...
19778    johannesburg reuters congolese army commander ...
5862     london reuters united state switch course clim...
10102    hate antifa well left really want associate vi...
                               ...
4849     beijing reuters warm word chinese president xi...
14431    never seems shortage smug know self righteous ...
6406     many united state come logical decision donald...
8100     washington reuters u senate vote soon wednesda...
5722     reuters highlight day u president donald trump...
Name: text, Length: 28000, dtype: object

In [36]:
vec_train_data = vectorizer.fit_transform(train_data)

In [37]:
vec_test_data = vectorizer.fit_transform(test_data)

In [38]:
vec_train_data = vec_train_data.toarray()

In [39]:
vec_test_data = vec_test_data.toarray()

In [40]:
vec_train_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(28000, 50000))

In [41]:
training_data = pd.DataFrame(vec_train_data, columns = vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_test_data, columns = vectorizer.get_feature_names_out())

In [42]:
training_data

,aaf,aapl,aaron,aarp,ab,aba,aba aslani,ababa,aback,abad,...,zor city,zor province,zuckerberg,zuckerberg said,zuma,zuma ex,zuma former,zurich,zurich reuters,zweiman
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Model - Naive Bayes

In [43]:
from sklearn.naive_bayes import MultinomialNB

In [44]:
clf = MultinomialNB()

In [45]:
clf.fit(training_data, train_label)

MultinomialNB()

In [46]:
pred = clf.predict(testing_data)

In [47]:
test_label

6237     1
2091     1
22731    1
22938    1
19211    1
        ..
192      1
18996    1
7628     0
21412    0
12396    0
Name: label, Length: 7000, dtype: int64

In [48]:
pred

array([1, 1, 1, ..., 0, 0, 0], shape=(7000,))

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
accuracy_score(test_label,pred)

0.6718571428571428

In [51]:
pred_train = clf.predict(training_data)

In [52]:
accuracy_score(train_label,pred_train)

0.959

In [66]:
txt = input('Enter a txt')

Enter a txt WASHINGTON (Reuters) - The top Republican in the U.S. House of Representatives said on Wednesday that Congress was working on a package of reforms that would prohibit using taxpayer money for settlements in sexual harassment claims lodged against lawmakersâ€™ offices. â€œThatâ€™s among the things weâ€™re working on right now,â€ House Speaker Paul Ryan said in an interview with Wisconsin radio station WISN a week after three lawmakers said they were stepping down after sexual harassment or misconduct claims.A wave of sexual misconduct allegations has emerged in recent weeks against high-profile figures in journalism, entertainment and politics. Democratic Representative John Conyers resigned after reports he had used public funds to settle a womanâ€™s claim. Conyers acknowledged his office had settled with a former staffer over harassment allegations, but denied wrongdoing. The congressional office that handles employment disputes  also said it had paid settlements on two claims involving sex discrimination allegations and one sexual harassment accusation since 2013. Politico reported that the sexual harassment settlement, which amounted to $84,000, was made on behalf of Texas Republican Representative Blake Farenthold. In a statement after he reached a settlement agreement in 2015, Farenthold denied engaging in any wrongdoing.

In [69]:
news = clean_row(('txt'))
predct = clf.predict(vectorizer.transform([news]).toarray())
if predct == 0:
    print("Its a true news**")
else:
    print("Its a fake news !!")

Its a fake news !!

C:\Users\Dilson\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(